In [ ]:
# Part 1
# Problem 1
import numpy as np
if __name__ == "__main__":
    arr = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]], dtype=float)
    print("Array =")
    print(arr)
    print("Data Type of the Array =", arr.dtype)
    print("Number of dimensions of the Array =", arr.ndim)
    print("Shape of the Array =", arr.shape)
    print("Size of the Array =", arr.size)
    print("Number of bytes used by each element of the Array =", arr.itemsize)
    print("Total bytes used by the Array =", arr.nbytes)
    print("Memory layout information =", arr.flags)

Array =
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Data Type of the Array = float64
Number of dimensions of the Array = 2
Shape of the Array = (3, 3)
Size of the Array = 9
Number of bytes used by each element of the Array = 8
Total bytes used by the Array = 72
Memory layout information =   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [ ]:
# Problem 2
import numpy as np
if __name__ == "__main__":
    arr2 = 3 * np.ones((4, 5), dtype=float)

    print("Array =")
    print(arr2)
    print("Shape =", arr2.shape)
    print("Data Type =", arr2.dtype)


Array =
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
Shape = (4, 5)
Data Type = float64


In [ ]:
# Problem 3
import numpy as np
if __name__ == "__main__":
    arr3 = np.full((4, 5), 3.0, dtype=float)
    print("Array =")
    print(arr3)
    print("Shape =", arr3.shape)
    print("Data Type =", arr3.dtype)
    print("Number of dimensions =", arr3.ndim)
    print("Size =", arr3.size)
    print("Item size =", arr3.itemsize)
    print("Total bytes =", arr3.nbytes)
    print("Memory layout information =", arr3.flags)

Array =
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
Shape = (4, 5)
Data Type = float64
Number of dimensions = 2
Size = 20
Item size = 8
Total bytes = 160
Memory layout information =   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [ ]:
# Problem 4
import numpy as np
if __name__ == "__main__":
    arr4 = np.fromfunction(lambda i, j: np.abs((i + 1) - 3 * (j + 1)) / 2, (3, 3), dtype=int)

    print("Array =")
    print(arr4)
    print("Shape =", arr4.shape)
    print("Data Type =", arr4.dtype)

Array =
[[1.  2.5 4. ]
 [0.5 2.  3.5]
 [0.  1.5 3. ]]
Shape = (3, 3)
Data Type = float64


In [ ]:
# Problem 5
import numpy as np
if __name__ == "__main__":

    arr5 = np.diag([1, 2, 3, 4])

    print("Array =")
    print(arr5)
    print("Shape =", arr5.shape)
    print("Data Type =", arr5.dtype)


Array =
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Shape = (4, 4)
Data Type = int64


In [ ]:
# Problem 6
import numpy as np
if __name__ == "__main__":
    arr6 = np.array([[0, 1, 2, 3, 4],
                     [1, 2, 3, 4, 5],
                     [2, 3, 4, 5, 6],
                     [3, 4, 5, 6, 7]])

    print("Original Array =")
    print(arr6)
    new_arr = arr6[0:3, 0:3]
    print("New Array =")
    print(new_arr)

Original Array =
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
New Array =
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
# Part 2
# Problem 1

import numpy as np
if __name__ == "__main__":
    A = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
    B = np.array([[1, 1, 1],
                  [2, 2, 2]])
    print("Matrix A =")
    print(A)
    print("Shape of A =", A.shape)

    print("\nMatrix B =")
    print(B)
    print("Shape of B =", B.shape)
    try:
        C = A + B
        print("\nMatrix C = A + B")
        print(C)
    except ValueError as e:
        print("\nError while adding A and B:", e)

Matrix A =
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of A = (3, 3)

Matrix B =
[[1 1 1]
 [2 2 2]]
Shape of B = (2, 3)

Error while adding A and B: operands could not be broadcast together with shapes (3,3) (2,3) 


In [ ]:
# Problem 3
B = np.array([[5,6],[7,8]])

result = [[0,0],[0,0]]

for i in range(2):
    for j in range(2):
        for k in range(2):
            result[i][j] += A[i][k] * B[k][j]

print(result)

[[np.int64(19), np.int64(22)], [np.int64(55), np.int64(64)]]


In [ ]:
# Problem 4
import numpy as np
def is_symmetric(matrix):
    return np.array_equal(matrix, matrix.T)

if __name__ == "__main__":
    A = np.array([[1, 2, 3],
                  [2, 5, 6],
                  [3, 6, 9]])
    B = np.array([[1, 0, 3],
                  [2, 5, 6],
                  [3, 6, 9]])

    print("Matrix A =\n", A)
    print("Is A symmetric? ->", is_symmetric(A))

    print("\nMatrix B =\n", B)
    print("Is B symmetric? ->", is_symmetric(B))